# DOTFILES SYMLINK [ HIDE ]

# --- misc rc ---
source ~/code/dotfiles/zsh/rc/prompt
source ~/code/dotfiles/zsh/rc/tab-titles

# --- plugins/tooling ---
# https://github.com/zsh-users/zsh-autosuggestions
source ~/code/dotfiles/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
# https://github.com/zsh-users/zsh-syntax-highlighting
# source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# https://github.com/asdf-vm/asdf/tree/release-v0.10.1
source ~/code/dotfiles/dependencies/asdf/asdf.sh

fpath=(~/code/dotfiles/dependencies/asdf/completions $fpath)
autoload -Uz compinit && compinit
alias zshrc="source ~/.zshrc && echo 'zshrc successfully reloaded'"